apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # "Delete" is not supported in static provisioning
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: same-volume  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      containerName: $SAME_PREFIX
    nodeStageSecretRef:
      name: azure-secret
      namespace: default