# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  - '^vendor$'
  - '^third_party$'
repos:
  - repo: git://github.com/Bahjat/pre-commit-golang
    rev: 85c26d4d1c8a086095a057bbdf8adf56af603ce4
    hooks:
      - id: go-fmt-import
        files: ./cmd/...
      - id: go-vet
        files: ./cmd/...
      - id: go-lint
        files: ./cmd/...
      - id: go-unit-tests
        files: ./cmd/...
      - id: gofumpt # requires github.com/mvdan/gofumpt
        files: ./cmd/...
      # Disabling as it does not appear to respect directory scoping
      # - id: go-err-check # requires github.com/kisielk/errcheck
      #   files: cmd
      - id: go-static-check # install https://staticcheck.io/docs/
        files: ./cmd/...
      - id: golangci-lint # requires github.com/golangci/golangci-lint
        files: ./cmd/...
