name: make-main

on:
  push:
    branches:
      - main
  schedule:
    - cron: "20 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16" # The Go version to download (if necessary) and use.
      - run: go version
      - name: Parse release version and set REL_VERSION
        run: python ./.github/scripts/get_release_version.py
      - name: Run Makefile
        run: make all
