name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build ${{ matrix.target_os }}_${{ matrix.target_arch }} binaries
    runs-on: ${{ matrix.os }}
    env:
      GOVER: 1.16
      GOLANGCILINT_VER: v1.37
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch }}
      GOPROXY: https://proxy.golang.org
      ARCHIVE_OUTDIR: dist/archives
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.2]
        os: [ubuntu-latest, macOS-latest]
        target_arch: [arm64, amd64]
        include:
          - os: ubuntu-latest
            target_os: linux
          - os: macOS-latest
            target_os: darwin
        exclude:
          - os: macOS-latest
            target_arch: arm
          - os: macOS-latest
            target_arch: arm64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16" # The Go version to download (if necessary) and use.
      - run: go version
      - run: 'echo "$PRIVATE_PEM" > /tmp/private.pem'
        shell: bash
        env:
          PRIVATE_PEM: ${{secrets.PRIVATE_PEM}}
      - name: Parse release version and set REL_VERSION
        run: python ./.github/scripts/get_release_version.py
      - name: Build
        run: |
          echo ${{ github.sha }} > Release.txt
          make build-same-tgz
        env:
          PRIVATE_KEY_PASSPHRASE: ${{secrets.PRIVATE_KEY_PASSPHRASE}}
      - name: Generate Changelog
        run: echo "# Release Notes" > ${{ github.workflow }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.BINARY_TARBALL }}
            ${{ env.BINARY_TARBALL_SIGNATURE }}
          body_path: ${{ github.workflow }}-CHANGELOG.txt
          repository: SAME-Project/SAMPLE-CLI-TESTER
        env:
          GITHUB_TOKEN: ${{ secrets.SAME_CLI_TESTER_GITHUB_TOKEN }}
